import PDFDocument from "pdfkit";

interface CertificateData {
  driverName: string;
  taxYear: string;
  hmrcSubmissionId: string;
  totalGrossIncome: number;
  personalAllowance: number;
  taxableIncome: number;
  estimatedTax: number;
  taxAlreadyPaid: number;
  balanceDue: number;
  submittedAt: Date;
}

export function generateTaxCertificatePDF(data: CertificateData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 60,
      info: {
        Title: `Tax Year Certificate — ${data.taxYear}`,
        Author: "My Cab Tax USA",
        Subject: `Final Declaration ${data.taxYear}`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 120;

    doc.rect(50, 40, pageWidth + 20, 100).fill("#065f46");
    doc.fill("#ffffff").fontSize(28).font("Helvetica-Bold");
    doc.text("TAX YEAR CERTIFICATE", 60, 60, { width: pageWidth, align: "center" });
    doc.fontSize(14).font("Helvetica");
    doc.text("My Cab Tax USA — Shield of Accuracy", 60, 100, { width: pageWidth, align: "center" });

    doc.fill("#1a1a1a");
    let y = 170;

    doc.fontSize(11).font("Helvetica-Bold").text("HMRC SUBMISSION ID", 60, y);
    doc.fontSize(16).font("Courier-Bold").text(data.hmrcSubmissionId, 60, y + 18);
    y += 50;

    doc.moveTo(60, y).lineTo(60 + pageWidth, y).stroke("#d1d5db");
    y += 15;

    const drawRow = (label: string, value: string, bold = false) => {
      doc.fontSize(11).font("Helvetica").text(label, 60, y, { width: pageWidth * 0.6 });
      doc.font(bold ? "Helvetica-Bold" : "Helvetica").text(value, 60 + pageWidth * 0.6, y, { width: pageWidth * 0.4, align: "right" });
      y += 24;
    };

    doc.fontSize(13).font("Helvetica-Bold").text("CERTIFICATE DETAILS", 60, y);
    y += 25;

    drawRow("Driver Name", data.driverName);
    drawRow("Tax Year", data.taxYear);
    drawRow("Submission Date", data.submittedAt.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }));

    y += 10;
    doc.moveTo(60, y).lineTo(60 + pageWidth, y).stroke("#d1d5db");
    y += 15;

    doc.fontSize(13).font("Helvetica-Bold").text("TAX BREAKDOWN", 60, y);
    y += 25;

    const fmt = (n: number) => `£${Math.abs(n).toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

    drawRow("Total Gross Income", fmt(data.totalGrossIncome));
    drawRow("Personal Allowance", `-${fmt(data.personalAllowance)}`);
    drawRow("Taxable Income", fmt(data.taxableIncome), true);

    y += 5;
    doc.moveTo(60, y).lineTo(60 + pageWidth, y).stroke("#e5e7eb");
    y += 12;

    drawRow("Estimated Tax (banded rates)", fmt(data.estimatedTax));
    drawRow("Tax Already Paid (PAYE)", `-${fmt(data.taxAlreadyPaid)}`);

    y += 5;
    doc.moveTo(60, y).lineTo(60 + pageWidth, y).stroke("#065f46").lineWidth(2);
    y += 12;
    doc.lineWidth(1);

    doc.fontSize(13).font("Helvetica-Bold").text("REMAINING BALANCE DUE", 60, y, { width: pageWidth * 0.6 });
    doc.fontSize(16).font("Helvetica-Bold").text(fmt(data.balanceDue), 60 + pageWidth * 0.6, y - 2, { width: pageWidth * 0.4, align: "right" });
    y += 40;

    doc.rect(60, y, pageWidth, 80).fill("#ecfdf5").stroke("#6ee7b7");
    doc.fill("#065f46").fontSize(12).font("Helvetica-Bold");
    doc.text("SHIELD OF ACCURACY", 80, y + 12, { width: pageWidth - 40, align: "center" });
    doc.fontSize(10).font("Helvetica").fill("#047857");
    doc.text(
      "This certificate confirms that the above tax return was prepared using the MCTUSA Tax Engine with AI-powered error checking, quarterly cross-validation, and IRS/HMRC compliance verification.",
      80, y + 32, { width: pageWidth - 40, align: "center" }
    );
    y += 100;

    doc.fill("#9ca3af").fontSize(9).font("Helvetica");
    doc.text(
      `Generated by My Cab Tax USA on ${new Date().toLocaleDateString("en-GB")}. This document is for record-keeping purposes. Retain for at least 7 years per HMRC guidance.`,
      60, y, { width: pageWidth, align: "center" }
    );

    doc.end();
  });
}
